spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/propertyapp
spring.datasource.username=postgres
spring.datasource.password=postsql987

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
